baseURL: https://zoftdev.github.io/knowledge
languageCode: en-us
title: Hlex
theme: "PaperMod"

params:
  homeInfoParams:
    Title: Hlex'note ðŸ˜Ž
    Content: This is something I want to share with you.

  socialIcons: # optional
    # - name: "github"
    #   url: "https://github.com/zoftdev"
    # # - name: "youtube"
    # #   url: "https://www.youtube.com/channel/XXX"
    # - name: "twitter"
    #   url: "https://twitter.com/zoftdev"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    # - name: "rss"
    #   url: "https://XXX.github.io/index.xml"
  ShowReadingTime: true
  author: "Hlex"
  contact: "hlex.news@gmail.com"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true

 #Google Analytics 4 optional
  env: #production
  GoogleAnalytics: "G-00000XXXXX" 
  sitemap:
    changefreq: daily
    filename: sitemap.xml
    priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
